version: '0.1'
services:
  db:
    image: postgres:latest
    container_name: lunatic-db
    ports:
     - 5432:5432
    environment:
      POSTGRES_DB: LunaticDB
      POSTGRES_USER: lunatic
      POSTGRES_PASSWORD: lunatic
    networks:
      - db_conn
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lunatic -d LunaticDB"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrator:
    build:
      context: ./lunatic-api
      dockerfile: ./Lunatic.Migrator.Dockerfile
    container_name: lunatic-migrator
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - db_conn
    depends_on:
      db:
        condition: service_healthy
  api:
    build:
      context: ./lunatic-api
      dockerfile: ./Dockerfile
    container_name: lunatic-api
    ports:
      - 8080:8080
    networks:
      - db_conn
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

networks:
  db_conn:
    driver: bridge

