version: '0.1'
services:
  db:
    image: postgres:latest
    container_name: lunatic-db
    ports:
     - 5432:5432
    environment:
      POSTGRES_DB: LunaticDB
      POSTGRES_USER: lunatic
      POSTGRES_PASSWORD: lunatic
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

