name: Lunatic CI

on:
  push:
    branches: [ "gbi-dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Luantic

    defaults:
      run:
        working-directory: ./lunatic-api
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Make Coverage
      run: dotnet test --collect:"XPlat Code Coverage" --results-directory TestsResults

    - name: test sometthing
      run: pwd

    - name: test sometthing
      run: mv -n  /home/runner/work/lunatic/lunatic/lunatic-api/TestsResults/**/*.xml  /home/runner/work/lunatic/lunatic/lunatic-api/TestsResults


    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2.2.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        format: cobertura
        file: /home/runner/work/lunatic/lunatic/lunatic-api/TestsResults/coverage.cobertura.xml
        debug: true

