name: Lunatic CI

on:
  push:
    branches: [ "gbi-dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Luantic

    defaults:
      run:
        working-directory: ./lunatic-api
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Make Coverage
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2.2.3

