
name: Lunatic Coverage

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Luantic

    defaults:
      run:
        working-directory: ./lunatic-api
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Make Coverage
      run: dotnet test --collect:"XPlat Code Coverage" --results-directory TestsResults

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2.2.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        format: cobertura
        file: /home/runner/work/lunatic/lunatic/lunatic-api/TestsResults/**/*.xml

